### ISSUE TITLE
Support for nested input variables 

### ISSUE THREAD

**Issue by paulrostorp** [shuttl-io/go-graphql-client#1]
Does this library support nested input arguments ?

```
mutation { 
    someOperation(input: { name: "foo" }) {
       response
    }
}
```

**Comment by radding** [comment]
Hiya! :wave: Thanks for reaching out!

Yes, this library does support nested input arguments! All though the way that the library is set up, it must be a variable to the GraphQL query:

```golang
input := struct {
       Name string `json:"name"`
}{
	Name: "foo",
}
req.Mutation(&struct {
	SomeOperation struct {
		Response string `json:"response"`
	} `json:"example" gql_params:"input:FooObj"`
}{})
    .WithVariable("input", input)
    .Send()

```

The built in Simple HTTP library will JSON serialize all variables and the query string and send it as a HTTP POST to the API.

**Comment by paulrostorp** [comment]
~~Hi,
Thanks for your response, I gave this a shot but without any luck 😢 It might be that it is the graphQL server I am targeting that is at fault, but it is a third party API, so I have no way of logging that actual request that was sent. The expected request does succeed when running via `curl`...~~

Edit: I got it working, not sure what I did wrong, but it works now 🙂
